FIX: Getting with index caused "unsupported operand type(s) for +: 'NoneType' and 'int'".
Fix newset.clauses["offset"] = None -> 0
  File "./lib/macaron.py", line 970, in __getitem__
    newset.clauses["offset"] = newset.clauses["offset"] + start
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'